---
name: st2_pkg_test_and_promote_unstable_u16_enterprise
pack: st2ci
description: Test and promote unstable packages
enabled: true

trigger:
  type: core.st2.CronTimer
  parameters:
    timezone: US/Pacific
    hour: 15
    minute: 0
    second: 0

criteria: {}

action:
  ref: st2ci.st2_pkg_test_and_promote_enterprise
  parameters:
    hostname: st2-ent-pkg-unstable-u16
    distro: UBUNTU16
    release: unstable
