---
name: st2_pkg_e2e_test_ubuntu18_on_st2_pr
description: Run Ubuntu18 end-to-end test on 'StackStorm/st2' PRs and update GitHub status
pack: st2ci
enabled: false

trigger:
    type: circle_ci.build_event

criteria:
    trigger.body.payload.vcs_url:
        type: equals
        pattern: "https://github.com/StackStorm/st2"
    # branch not starting with 'master' or 'vX.Y'
    trigger.body.payload.branch:
        type: regex
        pattern: "^(?!master|v[0-9]+\\.[0-9]+).*$"
    trigger.body.payload.has_artifacts:
        type: equals
        pattern: true
    trigger.body.payload.build_parameters:
        type: exists
        pattern: CIRCLE_JOB
    # limit to 'packages' sub-task in CircleCI workflow
    trigger.body.payload.build_parameters.CIRCLE_JOB:
        type: equals
        pattern: packages
    # See bug: https://discuss.circleci.com/t/wrong-data-in-webhook-payload-for-workflows/15076
    # when 'pull_requests' payload is included even for commits outside of PRs
    trigger.body.payload.pull_requests[0]:
        type: contains
        pattern: url
    trigger.body.payload.outcome:
        type: equals
        pattern: success

action:
    ref: st2ci.st2_pkg_e2e_test
    parameters:
        hostname: "pkg-e2e-test-ubuntu18-pr-st2-{{trigger.body.payload.build_num}}"
        distro: UBUNTU18
        pkg_env: staging
        release: unstable
        dev_build: "st2/{{trigger.body.payload.build_num}}"
        initial_commit: "{{trigger.body.payload.vcs_revision}}"
        triggering_commit_url: |
          COMMITTER: {{trigger.body.payload.author_name}}
          PULL_REQUEST: {{trigger.body.payload.pull_requests[0].url}}
          PKG_BUILD_URL: {{trigger.body.payload.build_url}}
          DIFF: {{trigger.body.payload.compare}}
