---
name: st2_pkg_test_and_promote_unstable_el8_enterprise
pack: st2ci
description: Test and promote unstable packages
enabled: false

trigger:
  type: core.st2.CronTimer
  parameters:
    timezone: US/Pacific
    hour: 9
    minute: 0
    second: 0

criteria: {}

action:
  ref: st2ci.st2_pkg_test_and_promote_enterprise
  parameters:
    hostname: st2-ent-pkg-unstable-el8
    distro: RHEL8
    release: unstable
