name: st2_pkg_test_unstable_u16
description: Run package tests on package build
pack: st2ci
enabled: true

trigger:
    type: circle_ci.build_event

criteria:
    trigger.body.payload.branch:
        type: equals
        pattern: master
    trigger.body.payload.vcs_url:
        type: equals
        pattern: "https://github.com/StackStorm/st2-packages"
    trigger.body.payload.outcome:
        type: equals
        pattern: success
    trigger.body.payload.build_parameters.ST2_GITREV:
        type: equals
        pattern: master

action:
    ref: st2ci.st2_pkg_e2e_test
    parameters:
        distro: UBUNTU16
        hostname: "st2-pkg-unstable-u16-{% if trigger.body.payload.build_parameters %}{{trigger.body.payload.build_parameters.ST2_COMMIT_SHA | truncate(10, False, '')}}{% else %}{{trigger.body.payload.vcs_revision | truncate(10, False, '')}}{% endif %}"
        pkg_env: staging
        release: unstable
        triggering_commit_url: "PKG_BUILD_URL: {{trigger.body.payload.build_url}} {% if trigger.body.payload.build_parameters %}\n COMMITTER: {{trigger.body.payload.build_parameters.COMMITTER}} \n DIFF: {{trigger.body.payload.build_parameters.GITHUB_URL}} \n CIRCLE: {{trigger.body.payload.build_parameters.CIRCLE_URL}} {% else %} \n COMMITTER: {{trigger.body.payload.author_name}} \n DIFF: {{trigger.body.payload.compare}} {% endif %}"
